### PR TITLE
update repo url in Cargo.toml

### PR DESCRIPTION
**Pull request by Skgland**
fixes rust-lang/gccjit.rs#40

### CODE REVIEW

**Review by antoyo — APPROVED** [review]
I'll fix the clippy warnings in another PR.

**Comment by antoyo** [comment]
I fixed the clippy warnings in #43. Please rebase to make the CI pass.

**Comment by Skgland** [comment]
Ok, I haved rebased the PR

**Comment by antoyo** [comment]
Thanks for your contribution!

**Pull request merged**
